services:
  - type: web
    name: changequo
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "Change Quo"
      - key: APP_URL
        value: "https://changequo.onrender.com"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:1wWf5KHtdnNCU3beG42ECrqpZJHGTjZbPPWpYWyDkvg="
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-12f1b6fc-change-quo.f.aivencloud.com
      - key: DB_PORT
        value: "26704"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: "false"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
